### PR TITLE
Fix slideshare link tests

### PR DESCRIPTION
**Pull request by ehelms**
On Travis, the slideshare links are throwing 999 failure codes which
appear to be due being blocked.

### CODE REVIEW

**Comment by beav** [comment]
looks good to me, the only change is `data-proofer-ignore`?

**Comment by ehelms** [comment]
Yea - tells the test runner to ignore those particular links since they are being blocked from Travis it appears.

**Comment by ehelms** [comment]
@beav anything else or care to ACK?

**Comment by beav** [comment]
@ehelms ACK from me :cat2:

**Pull request merged**
