### PR TITLE
Added workflow diagram

### PR DESCRIPTION
**Pull request by lzap**

### CODE REVIEW

**Comment by lzap** [comment]
Re [test] I believe this was not my fault.

**Comment by ehelms** [comment]
What do you think about a higher level diagram to go with this? From a user perspective, trying to read this guide and understand how do they take advantage of and use this feature, I am not seeing how the verbose sequence diagram helps. I think, for those that want to dig into and understand the overall process it helps. I might would think of it as basic and advanced sections.

**Comment by lzap** [comment]
I intentionally made the most complex scenario. I think we need to communicate clearly what happens behind the scenes. And I need this to be reviewed properly first, because I am not sure about all the bits. Let's push this into the manual (a new Advanced section perhaps?) and then discuss 10,000 ft diagrams. We need this.

**Comment by danilopopeye** [comment]
the number `21` seems odd to me.

    Proxy->Foreman:forwards Kickstart request

is this ok?

**Comment by lzap** [comment]
Katello configures templates API in proxy, so it makes sense.

**Comment by stbenjam** [comment]
[test]

**Comment by ehelms** [comment]
[test]

**Comment by lzap** [comment]
Giving up with this one.

**Pull request closed without merging**
