### PR TITLE
Really fix test failures

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by ehelms** [comment]
APT

**Comment by stbenjam** [comment]
The travis job isn't working, and not sure why, it's not realizing the changes in these  PR in the KATELLO-2.3 branch.

**Comment by stbenjam** [comment]
Ah maybe this, something  weird with the git config on travis slaves

`fatal: empty ident name (for <travis@testing-worker-linux-da6418d7-1-19977-linux-4-76657913.(none)>) not allowed`

**Comment by ehelms** [comment]
I didn't think travis would test branch to branch properly?

**Comment by stbenjam** [comment]
No it worked here, I wrote deploy.rb stuff to be aware of the PR branches.  On my list of things to look at.

**Pull request closed without merging**
