### PR TITLE
marking 2.4 as latest

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by jlsherrill** [comment]
To be merged once 2.4 is released

**Comment by stbenjam** [comment]
APT, I restarted the travis build, looked like slideshare.net was just offline when it ran.

**Comment by jlsherrill** [comment]
@stbenjam i think this issue has been around for a while, i haven't seen master pass for some time

**Comment by jlsherrill** [comment]
Looks like for some reason fetching slideshare from within travis isn't working.  Candlepin.org also seems to be down atm even outside of travis

**Comment by stbenjam** [comment]
Weird, it's nothing caused by this PR, so ACK

**Pull request merged**
