### PR TITLE
Refs #15845 - add katello-capsule pkg to docs

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by ehelms** [comment]
Is there a packaging PR to go with this (or go first) that has this RPM requiring the installer package?

**Comment by jlsherrill** [comment]
Why yes there is a packaging PR:  https://github.com/Katello/katello-packaging/pull/259

**Comment by ehelms** [comment]
@jlsherrill you are correct there IS a packaging PR, there is not however a packaging PR related to my question :)

**Comment by jlsherrill** [comment]
@ehelms https://github.com/Katello/katello-packaging/pull/262

that was intended to be in the first PR

**Comment by ehelms** [comment]
ACK

**Pull request merged**
