### PR TITLE
Set 3.1 as latest version

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by stbenjam** [comment]
ACK

**Comment by ehelms** [comment]
Want to update the side board too (for relese announcement) ?

**Comment by stbenjam** [comment]
We should probably trim some of the older announcements as well, it's getting a little long.

**Comment by jlsherrill** [comment]
added new announcement, got rid of old ones pre-3.0

**Comment by ehelms** [comment]
ACK for me

**Comment by stbenjam** [comment]
ACK from me too

**Pull request merged**
