### PR TITLE
refs #11787 - look up foreman version in hash instead

### PR DESCRIPTION
**Pull request by stbenjam**
The problem is the master _config.yml gets merged with the individual version's _config.yaml, so it was always setting foreman_version to nightly. Using a hash will fix it.

Also to 2.3 and 2.4: https://github.com/Katello/katello.org/pull/205, https://github.com/Katello/katello.org/pull/206

### CODE REVIEW

**Comment by beav** [comment]
@stbenjam the new var didn't populate for me when I ran `jekyll serve --watch --host <ip>` and viewed the docs in the browser. For example, the rpm url was `yum -y localinstall http://yum.theforeman.org//el6/x86_64/foreman-release.rpm` (note double slash in path).

How do you get it to populate when testing locally?

**Comment by stbenjam** [comment]
That's because `site.version` isn't defined yet.  It's quite convoluted, you have to use the `deploy` branch and `./deploy.rb --pr 204` might be enough

**Comment by beav** [comment]
`/deploy.rb --pr <pr>` populated everything as nightly (including #205 and #206), I think my local test may not be correct :panda_face: 

the change itself is simple enough though, looks good to me

**Comment by stbenjam** [comment]
Let me come up with a way to test it locally, this branching stuff causes more headaches for me than anything else.  Everytime I touch it, I wish katello.org was a monolithic repo

**Comment by stbenjam** [comment]
Will just fix it in deploy.rb so the current version works instead of going this route:
https://github.com/Katello/katello.org/pull/209

**Pull request closed without merging**
