### PR TITLE
Redirect docs to new pages on theforeman.org

### PR DESCRIPTION
**Pull request by ehelms**
II I have not been able to test these htaccess redirects in real time. They are based on some documentation and generators sites.

### CODE REVIEW

**Comment by ehelms** [comment]
Here is the htaccess change live in a test environment -- http://site-ehelms.rhcloud.com/

**Comment by stbenjam** [comment]
This is great, thanks for setting up the test environment.  Deep docs link redirect - which is AWESOME.

There does seem to be a problem with some of the links where we converted from content_views.md to index.md.

E.g. 3.2 side bar links to http://site-ehelms.rhcloud.com/docs/3.2/user_guide/content_views/content_views.html which 404's on theforeman.org, it's index.html there.

**Comment by ehelms** [comment]
Updated to include direct links for the renamed pages. I did update my test site but it does not seem to be picking up my changes to that file.

**Comment by stbenjam** [comment]
The change looks ok though, ACK from me

**Comment by jlsherrill** [comment]
ACK from me too!

**Pull request merged**
