### PR TITLE
Redirect Media page theforeman.org/media.html

### PR DESCRIPTION
**Pull request by ehelms**
Add use of jekyll-redirect-from to redirect individual pages as
we transition to theforeman.org

### CODE REVIEW

**Comment by ehelms** [comment]
@stbenjam Please take a look at this, as I think it is the best solution I could find to achieve the redirects you had in mind.

**Comment by ehelms** [comment]
@stbenjam How about this instead?

**Comment by stbenjam** [comment]
Sure that's fine - assuming that works on the container, no way for me to test that.  And we'll have broken tests forever if we do it that way initially.  I just meant the HTML redirects are fine and we could script creating the .htaccess once everything's moved

**Comment by ehelms** [comment]
@stbenjam here is the htaccess in action -- www.katello.org/blah  (Cause I wanted to ensure it worked as well)

**Comment by ehelms** [comment]
I guess I can go either way or add both. The htaccess does feel cleaner/quicker. The HTML version does keep tests from breaking and shows a mid-load screen for users. But I also like that with htaccess we get to literally delete code along the way.

@jlsherrill did you have any opinion one way or the other?

**Comment by stbenjam** [comment]
I'm fine with the .htaccess, if we just disable travis on this repo and commit to moving everything relatively quickly (a few months)

**Comment by stbenjam** [comment]
But if the site's going to be around for years, without the tests it'll revert to the way it was with broken links everywhere

**Comment by ehelms** [comment]
My plan was to begin moving everything with this being the opening salvo.

**Comment by stbenjam** [comment]
ACK from me then, let's do it

**Pull request merged**
