### PR TITLE
Add symlink to public data dir on openshift during build

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
The current strategy involves building public, committing it to git and pushing to Openshift. This results in the Openshift gear running out of space as the size of public grows and the git repo grows and then requires cleaning. This strategy changes to building public, syncing that to the Openshift data directory and ensuring there is a symlink to public. I tested this here -- http://site-ehelms.rhcloud.com/docs/3.0/

[1] https://github.com/theforeman/foreman-infra/blob/master/puppet/modules/jenkins_job_builder/files/theforeman.org/scripts/deploy_katello_site.sh

**Comment by ehelms** [comment]
@stbenjam @johnpmitsch when you get some time, would appreciate your thoughts on this approach change.

**Comment by johnpmitsch** [comment]
@ehelms I don't know enough about the katello.org deployment yet to give a thorough answer, but I would say symlinking duplicate content to save space is a good strategy (especially if we have been running out of space) and clicking around on your test site is working fine.

**Comment by jlsherrill** [comment]
ACK from me

**Comment by stbenjam** [comment]
ACK from me too

**Pull request merged**
