### PR TITLE
Change front page to tell users about new docs

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by it-praktyk** [comment]
Please check if your pull request resolve issue #352 . Thx.

**Comment by ehelms** [comment]
@it-praktyk it does, as this removes that from this front page

**Comment by stbenjam** [comment]
It's odd to me that the most prominent link goes to 3.2 installation docs instead of the new landing page.  I know that `theforeman.org` link in the text goes there, but I wouldn't click on it.  I'd just skim it and see the big button and click it.

I also think this is a little verbose, how about just killing katello.org and redirecting to our plugin page? I think the only thing left is the developer guide, let's just get that moved.

**Comment by stbenjam** [comment]
Although I do get why you might not want to just surprise people by the redirect on "/", and get the word out we moved. In that case, I'd keep it simple and just say "We've moved!" and have a single button that links to theforeman.org katello page.

**Comment by ehelms** [comment]
I simplified it down per your suggestion. Let me know what you think.

**Comment by ehelms** [comment]
I also added an update to the README to point contributors to the new docs location.

**Comment by ehelms** [comment]
@stbenjam mind re-reviewing please?

**Review by stbenjam — APPROVED** [review]
Looks good to me!

**Comment by stbenjam** [comment]
Can you also edit the description of the repo on github to point users to theforeman.org repo?

**Comment by ehelms** [comment]
Done!

**Pull request merged**
