### PR TITLE
Update docs to use scenario-based foreman-installer

### PR DESCRIPTION
**Pull request by bbuckingham**
This is an initial commit to incorporate documentation changes to support
the scenario-based foreman-installer.  With these changes, the katello-installer
and capsule-installer will go away and the user will use the foreman-installer
providing the desired --scenario input (e.g. 'foreman', 'katello', 'capsule').

Note:
~~- This PR does not yet include details on setting up the development environment using the scenario-based installer.~~
- This PR updates the 'upgrade' section; however, upgrades have not yet been tested for this release; therefore, there may be modifications needed as that work is done.

### CODE REVIEW

**Comment by mbacovsky** [comment]
Looks good and complete (with the exception of devel page). 

Maybe it would help to update the development section without testing (similarly to the upgrade one) and have it merged sooner and fix the potential issues in separate PR.

**Comment by bbuckingham** [comment]
Rebased the commit to update the developer documentation.  We'll now point the developer to using katello-deploy as the supported method to set up a development environment.  That tool allows developers to set the environment up using vagrant or using their own VM; therefore, no need to duplicate procedures.

**Comment by ehelms** [comment]
ACK! Thanks for this update @bbuckingham

**Comment by bbuckingham** [comment]
@mbacovsky, @ehelms, thanks guys!

**Pull request merged**
