### PR TITLE
Fix broken link to theforeman.org

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
Need ACK regardless of Travis, because the bad link is also in 2.2 branch.

**Comment by ehelms** [comment]
The change does seem not be causing the failure, but the failures seem strange.

**Comment by stbenjam** [comment]
Weird, it did it twice, but only on a handful of links.  It looks like openshift unreliability, the errored out urls work for me though.

**Comment by ehelms** [comment]
Looks like a legitimate failure now.

**Comment by stbenjam** [comment]
It's failing in 2.2, this needs to be merged here and backported to 2.2 branch.

But maybe not needed at all if https://github.com/theforeman/theforeman.org/pull/383 is taken

**Comment by ehelms** [comment]
@stbenjam should we update this or is theforeman.org PR going to go in soon?

**Comment by stbenjam** [comment]
Sorry, got distracted with bugs - just updated the foreman PR, so I don't think we need this one anymore.

**Pull request closed without merging**
