### PR TITLE
Refs #12038 - add preupgrade script documentation

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by stbenjam** [comment]
Tests are failing because #250 changed the nightly URL's, not sure why that one passed tests to begin with.

**Comment by stbenjam** [comment]
Sorry it was #248.  Anyway, @jlsherrill would you move this to be a PR against master first and have it cherry-picked to the 3.0 branch?

**Comment by jlsherrill** [comment]
@stbenjam i can open it against master, but since this will only be useful for the 3.0 release, it made sense to just do it in the 3.0 branch.  Thoughts?

**Comment by stbenjam** [comment]
I thought we were supporting upgrades from N-2, so it'd be applicable as a note to 3.1 as well (and anyway adventurous enough to upgrade 2.4 to nightly for some reason)

**Comment by jlsherrill** [comment]
True, we have said that even though we never test it :)

**Comment by jlsherrill** [comment]
opened against master   https://github.com/Katello/katello.org/pull/265

**Comment by stbenjam** [comment]
ACK

**Pull request merged**
