### PR TITLE
Add upgrade note due to gutterball postgres error.

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by stbenjam** [comment]
My preference would be to fix what's causing this.  It happens consistently?

I'll try an upgrade this afternoon to see what happens for me

**Comment by ehelms** [comment]
That would be my preference in the end as well, however, given the nature of the error, and what it takes to reproduce it, I don't want to delay release 3 days waiting for it when as far as my testing can tell, the error is not harmful.

**Comment by stbenjam** [comment]
ACK, as long as there's a redmine ticket for the issue so we don't forget

**Comment by ehelms** [comment]
@stbenjam for this issue? it should only ever occur during the 2.1 to 2.2 upgrade. I don't know if its indicative of the types of issues we may hit in the future as modules change.

**Comment by stbenjam** [comment]
What about fixing it in 2.2.1? I think there's something fundamentally wrong here that should be understood, it's trying to create a database that already exists for gutterball.  Seems odd to just write that off.

**Comment by ehelms** [comment]
OK.. I'll file one. I tried parsing the logs to understand why it thinks it needs to regenerate it and tried some fixes but nothing worked for me in the end.

**Comment by stbenjam** [comment]
There's a few small differences between https://github.com/theforeman/puppet-foreman/blob/master/manifests/database/postgresql.pp and https://github.com/Katello/puppet-gutterball/blob/master/manifests/database.pp, but doesn't seem to be significant.  It may very well be a bug somewhere in puppetlabs-postgresql.

**Comment by ehelms** [comment]
I tried adding those without any luck before I ran the upgrade. The logs
are interesting, but I am just not seeing why even though it appears to
find the DB exists, it still fires the create.

On Wed, May 6, 2015 at 3:30 PM, Stephen Benjamin <notifications@github.com>
wrote:

> There's a few small differences between
> https://github.com/theforeman/puppet-foreman/blob/master/manifests/database/postgresql.pp
> and
> https://github.com/Katello/puppet-gutterball/blob/master/manifests/database.pp,
> but doesn't seem to be significant. It may very well be a bug somewhere in
> puppetlabs-postgresql.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Katello/katello.org/pull/159#issuecomment-99581097>.
>



-- 
Go Pack and War Eagle,
Eric D. Helms

Ph.D. Student - North Carolina State University

**Pull request merged**
