### PR TITLE
Fixed epel release links for installs

### PR DESCRIPTION
**Pull request by rothgar**
:+1:

### CODE REVIEW

**Comment by stbenjam** [comment]
@rothgar Thanks - I think this is a dupe of #104, just the branch name is different.  Can we close this?

**Comment by rothgar** [comment]
This one merges into 2.0 documentation and the other was for 2.1 documentation. Not sure if there was a way to push 1 merge to 2 branches.

**Comment by stbenjam** [comment]
Ah, right, sorry I thought they were both targeting 2.1.

**Comment by stbenjam** [comment]
@ehelms, this is a good example of when we need to make a change to the published versions of several branches.  GitHub's tools for this are not very good.  What's the workflow? 

So far we seem to be opening PR's directly against KATELLO-2.1 and KATELLO-2.0, like my upgrade PR was suggested  to go to the KATELLO-2.1 branch directly.

But I feel like nearly everything should only go to master and then:
  * At RC time, we branch to KATELLO-X.
  * Further changes continue to only go to master.  
  * Just before GA, someone submits a backport PR for all the appropriate changes to go to KATELLO-X.
  * During the life of the release, generic PR's like this would get flagged for backporting, and we'd have to handle getting it backported to older versions (say, we try to maintain the last 2) if necessary

That way we only need to ask community members for PR's to master, and a PR directly to a version branch should be rare.   

Does Jekyll have any other ways to define global variables? Like site.foreman_version, or site.epel7_url so the content of the installation/upgrade/etc docs are the same on all the branches.

**Comment by ehelms** [comment]
+1 to the process, using the backport flag similar to how it's been used for 2.1 is the best option I think as it reduces the overhead and burden of the PR submitter.

Jekyll allows defining any global variable - this is how I did the site.version support. Any item you add to a config file gets added to and made available via the `site` variable.

**Comment by stbenjam** [comment]
@ehelms Ok cool! I'll merge this for now so all 3 branches have the right EPEL link, and look at making the unique stuff into jekyll variables later this week. That should make it a bit easier to keep all the package URL's up to date.

Thanks @rothgar !

**Pull request merged**
