### PR TITLE
Include warning about rebooting to load new kernel + selinux policy

### PR DESCRIPTION
**Pull request by stbenjam**

### CODE REVIEW

**Comment by stbenjam** [comment]
Otherwise you get this mess and the installer fails: http://pastebin.com/DH7uPYwa

**Comment by ehelms** [comment]
ACK

**Comment by ehelms** [comment]
Is there a way to detect this at all?

**Comment by stbenjam** [comment]
I don't know enough about SElinux to say, maybe we can talk to @lzap to look more at the error, or whoever maintains pulp-selinux.  I asked on #pulp but nobody replied.

**Comment by ehelms** [comment]
Ok, I am fine with this, I was just thinking if there was an easy way to detect we could block the installer and warn the user.

**Pull request merged**
