### PR TITLE
Adding note about specific SELinux type required for writing to export

### PR DESCRIPTION
**Pull request by beav**
Patch was originally from @mccun934, updated with alteration for correct
context.

### CODE REVIEW

**Comment by beav** [comment]
This supercedes https://github.com/Katello/katello.org/pull/253, will close both once merged

**Comment by beav** [comment]
this needs the following for travis to be green

https://github.com/Katello/katello.org/pull/319
https://github.com/Katello/katello.org/pull/320
https://github.com/Katello/katello.org/pull/321
https://github.com/Katello/katello.org/pull/322
https://github.com/Katello/katello.org/pull/323
https://github.com/Katello/katello.org/pull/324

**Comment by johnpmitsch** [comment]
ACK

**Comment by beav** [comment]
:100: thanks

**Pull request merged**
