### PR TITLE
minor changes to Backup page

### PR DESCRIPTION
**Pull request by danilopopeye**
* correct wrong file in final check-up list	6f58870
* mark some parts with inline code blocks 912a722

---

PS.: I've made this fixes through the GitHub edit button, if you guys need me to rebase these commits, rename the branch or something more fancy let me know!

### CODE REVIEW

**Comment by ehelms** [comment]
Looks good, do you mind rebasing and squashing into a single commit?

**Comment by danilopopeye** [comment]
@ehelms done!

**Comment by ehelms** [comment]
@danilopopeye Thanks! if you are interested there is on going work to script this process -- https://github.com/Katello/katello-packaging/pull/24

**Comment by danilopopeye** [comment]
@ehelms I'll have a look, thanks! :clap:

**Comment by ehelms** [comment]
Going to go ahead and merge these changes, however, we should update these docs for the next release to use the scripts.

**Pull request merged**
