### PR TITLE
Fixes nightly urls

### PR DESCRIPTION
**Pull request by johnpmitsch**
"nightly" isn't showing up in our nightly docs for installation and upgrade urls. To test, deploy and then check docs > nightly installation instructions for the correct urls (should have /nightly/ in them)

### CODE REVIEW

**Comment by johnpmitsch** [comment]
This won't fix the old "Nightly" in the navigation under docs.  I will open up a PR for that as well and link it here.

**Comment by ehelms** [comment]
ACK

**Comment by johnpmitsch** [comment]
https://github.com/Katello/katello.org/pull/250 to remove the extra nightly option

**Comment by ehelms** [comment]
Thanks @johnpmitsch !

**Pull request merged**
